services:
  db:
    image: postgres:15
    container_name: pg-docker
    environment:
      POSTGRES_USER: rifan
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://rifan:12345678@db:5432/inventory_db


volumes:
  pgdata:
